import AdminSidebar from "@/components/admin/AdminSidebar/AdminSidebar";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hekto Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Toaster />
        <main className="grid  grid-cols-[300px_minmax(900px,_1fr)]">
          <AdminSidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
